In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("creditcard.csv")

In [3]:
df.shape

(284807, 31)

In [14]:
df.iloc[:,-1].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [22]:
def transform(x):
    return (x-x.min())/(x.max()-x.min())

In [24]:
df['Time']=transform(df['Time'])

In [25]:
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0  0.000000 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1  0.000000  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2  0.000006 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3  0.000006 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4  0.000012 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928   
1 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575   
4  0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [30]:
from sklearn.preprocessing import RobustScaler
rb=RobustScaler()

df['Amount']=rb.fit_transform(df['Amount'].to_numpy().reshape(-1,1))

In [31]:
df.head()

Time        V1        V2        V3        V4        V5        V6  \
0  0.000000 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1  0.000000  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2  0.000006 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3  0.000006 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4  0.000012 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928   
1 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575   
4  0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28    Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  1.783274      0  
1  0.167170  0.125895 -0.008983  0.014724 -0.269825      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  4.983721      0  
3  0.647376 -0.221929  0.062723  0.061458  1.418291      0  
4 -0.206010  0.502292  0.219422  0.215153  0.670579      0  

[5 rows x 31 columns]

In [15]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=.2,random_state=2)

In [34]:
from sklearn.tree import DecisionTreeClassifier

In [46]:
dt=DecisionTreeClassifier(max_depth=5)

In [47]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [48]:
y_prd=dt.predict(X_test)

In [100]:
from sklearn.metrics import confusion_matrix,f1_score

In [49]:
confusion_matrix(y_test,y_prd)

array([[56870,     8],
       [   19,    65]], dtype=int64)

In [50]:
from sklearn.svm import SVC

In [51]:
sv=SVC()

In [53]:
sv.fit(X_train,y_train)

SVC()

In [54]:
y_pred=sv.predict(X_test)

In [55]:
confusion_matrix(y_test,y_pred)

array([[56874,     4],
       [   17,    67]], dtype=int64)

In [56]:
from sklearn.metrics import precision_score,recall_score

In [209]:
print(f"sv_pre={precision_score(y_test,y_pred,average="macro")}")
print(f"sv_rec={recall_score(y_test,y_pred,average="macro")}")
print(f"dt_pre={precision_score(y_test,y_prd,average="macro")}")
print(f"dt_rec={recall_score(y_test,y_prd,average="macro")}")

sv_pre=0.9467944816392777
sv_rec=0.9448989898989899
dt_pre=0.9195097037793667
dt_rec=0.9148484848484848


In [61]:
new_df_f=df.loc[df['Class']==1]
new_df_nf=df.loc[df['Class']==0]

In [69]:
new_df=pd.concat([new_df_f,new_df_nf.sample(500)])

In [71]:
new_df=new_df.sample(992)

In [72]:
new_df.head()

Time        V1        V2        V3        V4        V5        V6  \
226376  0.836867  2.038100 -2.371303  0.479374 -1.264330 -2.229535  1.492429   
83417   0.346312 -3.215382 -0.364223 -1.261883  3.794949  0.711206 -1.316476   
246320  0.886193 -1.124233  0.854133  0.701236 -0.909368  0.231444 -0.251234   
176049  0.709570 -2.003460 -7.159042 -4.050976  1.309580 -2.058102 -0.098621   
149357  0.527079 -1.855061  1.554964 -1.405809  0.669327 -0.280230  1.178652   

              V7        V8        V9  ...       V21       V22       V23  \
226376 -2.634727  0.609113  0.434526  ... -0.024337  0.670647  0.135450   
83417  -5.165141  0.625278 -1.582301  ...  0.401341  0.152191 -0.934675   
246320 -0.072475  0.654139  0.005750  ... -0.090128 -0.532004 -0.034821   
176049  2.880083 -0.727484  1.460381  ...  1.244287 -1.015232 -1.800985   
149357 -3.459979 -2.815155  1.242229  ... -0.095308  0.946629 -0.297403   

             V24       V25       V26       V27       V28     Amount  Class  
226376  0.242189 -0.358709 -0.000631  0.100005 -0.027811   0.638580      0  
83417  -0.256148 -0.469403 -0.282496  0.866077 -0.433466  -0.224831      1  
246320  0.624215 -0.352069 -0.343737 -0.142513  0.090723  -0.205128      0  
176049  0.657586 -0.435617 -0.894509 -0.397557  0.314262  29.398030      1  
149357 -0.368344  0.198731 -0.078591  0.366709  0.073767   0.234193      1  

[5 rows x 31 columns]

In [73]:
X_train,X_test,y_train,y_test=train_test_split(new_df.iloc[:,:-1],new_df.iloc[:,-1],test_size=.2,random_state=2)

In [75]:
dt1=DecisionTreeClassifier(max_depth=5)

In [76]:
dt1.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=5)

In [77]:
y_prd=dt1.predict(X_test)

In [78]:
confusion_matrix(y_test,y_prd)

array([[96,  3],
       [14, 86]], dtype=int64)

In [79]:
sv1=SVC()

In [83]:
sv1.fit(X_train,y_train)

SVC()

In [85]:
y_pred=sv.predict(X_test)

In [86]:
print(f"sv_pre={precision_score(y_test,y_pred,average="macro")}")
print(f"sv_rcc={recall_score(y_test,y_pred,average="macro")}")
print(f"dt_pre={precision_score(y_test,y_prd,average="macro")}")
print(f"dt_rcc={recall_score(y_test,y_prd,average="macro")}")

sv_pre=0.9090909090909092
sv_rcc=0.89
dt_pre=0.9195097037793667
dt_rcc=0.9148484848484848


In [88]:
from sklearn.ensemble import RandomForestClassifier

In [184]:
rfc=RandomForestClassifier(n_estimators=80, max_depth=5,random_state=42)

In [185]:
rfc.fit(X_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=80, random_state=42)

In [186]:
y_pred=rfc.predict(X_test)

In [187]:
confusion_matrix(y_test,y_pred)

array([[97,  2],
       [11, 89]], dtype=int64)

In [179]:
print(f"rfc_pre={precision_score(y_test,y_pred,average="macro")}")
print(f"rfc_rec={recall_score(y_test,y_pred,average="macro")}")
print(f"f1_sc={f1_score(y_test,y_pred)}")

rfc_pre=0.9338430173292558
rfc_rcc=0.9298989898989899
f1_sc=0.9263157894736842


In [195]:
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression 

In [202]:
estimators=[
    ('rf',RandomForestClassifier(n_estimators=50)),
    ('gd',GradientBoostingClassifier()),
    ('svc',SVC()),
    
]

In [203]:
stclf=StackingClassifier(estimators=estimators, final_estimator=LogisticRegression(), cv=5, n_jobs=-1,)

In [204]:
stclf.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('rf', RandomForestClassifier(n_estimators=50)),
                               ('gd', GradientBoostingClassifier()),
                               ('svc', SVC())],
                   final_estimator=LogisticRegression(), n_jobs=-1)

In [205]:
y_pred=stclf.predict(X_test)

In [206]:
confusion_matrix(y_test,y_pred)

array([[97,  2],
       [ 9, 91]], dtype=int64)

In [208]:
print(f"stclf_pre={precision_score(y_test,y_pred,average="macro")}")
print(f"stcl_rec={recall_score(y_test,y_pred,average="macro")}")
print(f"f1_sc={f1_score(y_test,y_pred)}")

stclf_pre=0.9467944816392777
stcl_rec=0.9448989898989899
f1_sc=0.9430051813471503


# So now we get the best f1_sc, precision and recall value so we select StackingClassifier

# the End